# Generated by Django 5.2.6 on 2025-10-22 16:46
from django.db import migrations
from django.contrib.auth import get_user_model

# ¡¡CAMBIA ESTOS VALORES!!
ADMIN_USERNAME = 'admin'
ADMIN_EMAIL = 'admin@example.com'
ADMIN_PASSWORD = 'TuContraseñaSegura' # Pon una contraseña real aquí

def create_superuser(apps, schema_editor):
    """Crea un superusuario si no existe."""
    User = get_user_model()
    
    if User.objects.filter(username=ADMIN_USERNAME).exists():
        print(f'Superusuario {ADMIN_USERNAME} ya existe. No se hace nada.')
        return

    print(f'Creando superusuario: {ADMIN_USERNAME}')
    
    # Crea el superusuario
    User.objects.create_superuser(
        username=ADMIN_USERNAME,
        email=ADMIN_EMAIL,
        password=ADMIN_PASSWORD
    )

class Migration(migrations.Migration):

    dependencies = [
        # Cambia '0001_initial' por el nombre de tu migración anterior de 'api'
        ('api', '0001_initial'), 
        # También depende de la app 'auth' de Django
        ('auth', '0012_alter_user_first_name_max_length'), 
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]